In [1]:
#Create a random tensor with shape (7, 7).
import torch
tensor = torch.rand(7, 7)
print(tensor)


tensor([[0.2918, 0.1410, 0.4100, 0.4784, 0.2438, 0.2650, 0.5930],
        [0.0544, 0.7168, 0.2676, 0.0338, 0.2020, 0.3772, 0.2124],
        [0.7299, 0.2078, 0.5553, 0.9541, 0.6150, 0.7851, 0.4241],
        [0.0579, 0.4635, 0.5960, 0.0114, 0.4275, 0.3538, 0.6859],
        [0.7476, 0.1774, 0.0281, 0.7825, 0.8037, 0.1557, 0.7646],
        [0.4111, 0.9082, 0.7641, 0.6067, 0.0745, 0.4782, 0.3862],
        [0.4121, 0.5981, 0.9312, 0.0726, 0.2182, 0.6008, 0.9016]])


In [4]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
X=torch.rand(size=(1,7))
Y=torch.rand(size=(1,7))
Z=torch.mm(X,Y.T)
print(Z)
Z.shape


tensor([[2.3191]])


torch.Size([1, 1])

In [7]:
#Set the random seed to 0 and do 2 & 3 over again.
# Set manual seed
torch.manual_seed(3)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.1569],
         [2.7528],
         [2.7826],
         [1.8017],
         [0.8425],
         [1.8660],
         [1.6771]]),
 torch.Size([7, 1]))

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [9]:
#Perform a matrix multiplication on the tensors you created in 6
torch.matmul(X,Y.T)

tensor([[1.1569],
        [2.7528],
        [2.7826],
        [1.8017],
        [0.8425],
        [1.8660],
        [1.6771]])

In [11]:
#Find the maximum and minimum values of the output of 7.
max=torch.max(tensor)
min=torch.min(tensor)
max, min

(tensor(0.9541), tensor(0.0114))

In [13]:
#Find the maximum and minimum index values of the output of 7.
arg_max = torch.argmax(tensor)
arg_min = torch.argmin(tensor)
arg_max, arg_min

(tensor(17), tensor(24))

In [15]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
